name: Download MediaFire to GitHub Release

on:
  workflow_dispatch:
    inputs:
      mediafire_page_url:
        description: 'URL Halaman MediaFire (URL yang menampilkan tombol "Download")'
        required: true
        default: 'https://www.mediafire.com/file/...'
      release_tag:
        description: 'Tag rilis untuk mengunggah aset'
        required: true
        default: 'v1.0.0'

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract direct download URL
        id: get_download_url
        run: |
          PAGE_URL="${{ github.event.inputs.mediafire_page_url }}"
          
          # Attempt to fetch the HTML content and extract the download URL
          # This pattern looks for URLs starting with 'https://download' followed by numbers,
          # then a long string of alphanumeric characters and underscores,
          # and then the file path part of the URL.
          DOWNLOAD_URL=$(curl -sL "$PAGE_URL" | grep -o 'https://download[0-9]\{3,\}\.mediafire\.com/[a-zA-Z0-9_\-]*\/[a-zA-Z0-9\/_-]*\.zip')
          
          if [[ -z "$DOWNLOAD_URL" ]]; then
            echo "Error: Could not extract download URL from the provided page. Please check the URL and MediaFire's current structure."
            exit 1
          fi

          echo "Extracted Download URL: $DOWNLOAD_URL"
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
          
          # Extract a valid filename from the URL. This part might need adjustment
          # depending on how the filename is actually encoded in the URL.
          # For now, let's try to get the part after the last slash.
          FILENAME=$(echo "$DOWNLOAD_URL" | sed 's/.*\///')
          
          # Basic sanitization for filename
          FILENAME=$(echo "$FILENAME" | sed 's/[^a-zA-Z0-9._-]//g')
          
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Download file using the direct URL
        run: |
          # Use wget to download the file, and save it with the extracted filename
          # Add --content-disposition to try and use the filename from the server if available
          wget --content-disposition -O "${{ steps.get_download_url.outputs.filename }}" "${{ steps.get_download_url.outputs.download_url }}"

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.release_tag }}
          artifacts: "${{ steps.get_download_url.outputs.filename }}"
          allowUpdates: true
