name: Download MediaFire to GitHub Release

on:
  workflow_dispatch:
    inputs:
      mediafire_page_url:
        description: 'URL Halaman MediaFire'
        required: true
        default: ''
      release_tag:
        description: 'Tag rilis untuk mengunggah aset'
        required: true
        default: 'v1.0.0'

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Extract direct download URL and filename using yt-dlp
        id: get_download_info
        run: |
          # Use yt-dlp to get the direct download URL
          # The -g flag outputs the URL
          # The --get-filename flag outputs the original filename
          PAGE_URL="${{ github.event.inputs.mediafire_page_url }}"
          
          # Use --print-json to get structured output
          DOWNLOAD_INFO=$(yt-dlp --print-json "$PAGE_URL")
          DOWNLOAD_URL=$(echo "$DOWNLOAD_INFO" | jq -r '."url"')
          FILENAME=$(echo "$DOWNLOAD_INFO" | jq -r '."_filename"')

          if [[ -z "$DOWNLOAD_URL" || "$DOWNLOAD_URL" == "null" ]]; then
            echo "Error: Could not extract download URL from the provided page."
            exit 1
          fi

          echo "Extracted Download URL: $DOWNLOAD_URL"
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Download file using wget
        run: |
          wget -O "${{ steps.get_download_info.outputs.filename }}" "${{ steps.get_download_info.outputs.download_url }}"

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.release_tag }}
          artifacts: "${{ steps.get_download_info.outputs.filename }}"
          allowUpdates: true
